name: Cypress-e2e
on: push
jobs:
    cypress-run:
        runs-on: windows-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Cypress run
              uses: cypress-io/github-action@v6

              with: 
                command: npx cypress run
                browser: chrome

